# Generated by Django 5.0.14 on 2026-06-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='certificate_type',
            field=models.CharField(choices=[('PARTICIPATION', 'Participation'), ('FIRST', '🥇 First Place'), ('SECOND', '🥈 Second Place'), ('THIRD', '🥉 Third Place')], default='PARTICIPATION', max_length=20),
        ),
    ]
