# Generated by Django 5.0.14 on 2026-06-27 18:42

import events.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_studentprofile_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='student_id',
            field=models.CharField(max_length=10, unique=True, validators=[events.validators.validate_student_id]),
        ),
    ]
